# Generated by Django 6.0 on 2026-05-08 05:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0009_commercialdashboardreport_and_more'),
        ('production', '0008_productionsite_production_equals_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionZoneAllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('FIXED_WEIGHT', 'Fixed Weight'), ('FIXED_PERCENTAGE', 'Fixed Percentage')], default='FIXED_WEIGHT', help_text='Both methods are normalized per zone/day. If percentage values sum to 100 for a zone, the configured percentages are applied exactly.', max_length=30)),
                ('basis_value', models.DecimalField(decimal_places=4, help_text='Weight or percentage basis used in proportional allocation.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Reserved for future balance/manual methods. Lower values are evaluated first.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_allocation_rules', to='production.productionsite')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_allocation_rules', to='distribution.zone')),
            ],
            options={
                'verbose_name': 'Production Zone Allocation Rule',
                'verbose_name_plural': 'Production Zone Allocation Rules',
                'ordering': ['zone__region__dashboard_order', 'zone__dashboard_order', 'zone__name', 'priority', 'production_site__name'],
                'indexes': [models.Index(fields=['zone', 'is_active'], name='water_balan_zone_id_6a1574_idx'), models.Index(fields=['production_site', 'is_active'], name='water_balan_product_fc0311_idx'), models.Index(fields=['effective_start_date', 'effective_end_date'], name='water_balan_effecti_19b560_idx')],
            },
        ),
    ]
