# Generated by Django 6.0 on 2026-05-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0009_commercialdashboardreport_and_more'),
        ('production', '0008_productionsite_production_equals_supply'),
        ('water_balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionzoneallocationrule',
            options={'ordering': ['zone__region__dashboard_order', 'zone__dashboard_order', 'zone__name', 'rule_type', 'priority', 'production_site__name'], 'verbose_name': 'Production Zone Allocation Rule', 'verbose_name_plural': 'Production Zone Allocation Rules'},
        ),
        migrations.AddField(
            model_name='productionzoneallocationrule',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for an operational exception, such as offtake, shutdown, burst, or valve operation.', max_length=100),
        ),
        migrations.AddField(
            model_name='productionzoneallocationrule',
            name='rule_type',
            field=models.CharField(choices=[('MONTHLY_STANDARD', 'Monthly Standard'), ('OPERATIONAL_EXCEPTION', 'Operational Exception')], default='MONTHLY_STANDARD', help_text='Monthly standards are used by default; operational exceptions override standards for matching dates.', max_length=30),
        ),
        migrations.AddIndex(
            model_name='productionzoneallocationrule',
            index=models.Index(fields=['zone', 'rule_type', 'is_active'], name='water_balan_zone_id_7dbbde_idx'),
        ),
    ]
