# Generated by Django 6.0 on 2026-05-11 07:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0009_commercialdashboardreport_and_more'),
        ('metering', '0007_mobile_external_ids'),
        ('production', '0008_productionsite_production_equals_supply'),
        ('water_balance', '0002_alter_productionzoneallocationrule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBalanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('effective_start_date', models.DateField()),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_balance_models', to='distribution.zone')),
            ],
            options={
                'verbose_name': 'Water Balance Model',
                'verbose_name_plural': 'Water Balance Models',
                'ordering': ['zone__region__dashboard_order', 'zone__dashboard_order', 'zone__name', '-effective_start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WaterBalanceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('node_type', models.CharField(choices=[('PRODUCTION_SITE', 'Production Site'), ('MIXING_NODE', 'Mixing Node'), ('INTERMEDIARY', 'Intermediary')], default='MIXING_NODE', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_site', models.ForeignKey(blank=True, help_text='Link when this node represents a production site such as Water Works.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_balance_nodes', to='production.productionsite')),
            ],
            options={
                'verbose_name': 'Water Balance Node',
                'verbose_name_plural': 'Water Balance Nodes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WaterBalanceNodeInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_method', models.CharField(choices=[('SITE_PRODUCTION', 'Site Production'), ('METERED_TRANSFER', 'Metered Transfer'), ('RESIDUAL', 'Residual')], max_length=30)),
                ('confidence', models.CharField(choices=[('MEASURED', 'Measured'), ('MEASURED_ALLOCATED', 'Measured/Allocated'), ('ESTIMATED', 'Estimated'), ('MANUAL', 'Manual')], default='MEASURED', max_length=30)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_start_date', models.DateField(blank=True, null=True)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='water_balance.waterbalancenode')),
                ('production_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_balance_node_inputs', to='production.productionsite')),
                ('water_meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_balance_node_inputs', to='metering.watermeter')),
            ],
            options={
                'verbose_name': 'Water Balance Node Input',
                'verbose_name_plural': 'Water Balance Node Inputs',
                'ordering': ['node__name', 'priority', 'production_site__name'],
            },
        ),
        migrations.CreateModel(
            name='WaterBalanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(blank=True, help_text='Route label, for example Karati via Water Works.', max_length=200)),
                ('method', models.CharField(choices=[('FIXED_WEIGHT', 'Fixed Weight'), ('FIXED_PERCENTAGE', 'Fixed Percentage'), ('METERED_VOLUME', 'Metered Volume'), ('MIXING_NODE_SHARE', 'Mixing Node Share'), ('MANUAL_OVERRIDE', 'Manual Override')], max_length=30)),
                ('basis_value', models.DecimalField(blank=True, decimal_places=4, help_text='Percentage, fixed weight, or fallback basis depending on method.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('manual_volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence', models.CharField(choices=[('MEASURED', 'Measured'), ('MEASURED_ALLOCATED', 'Measured/Allocated'), ('ESTIMATED', 'Estimated'), ('MANUAL', 'Manual')], default='MEASURED_ALLOCATED', max_length=30)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_start_date', models.DateField(blank=True, null=True)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='water_balance.waterbalancemodel')),
                ('mixing_node', models.ForeignKey(blank=True, help_text='Mixing node used when method is mixing node share.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_rules', to='water_balance.waterbalancenode')),
                ('production_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_balance_rules', to='production.productionsite')),
                ('water_meter', models.ForeignKey(blank=True, help_text='Meter used when method is metered volume.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_balance_rules', to='metering.watermeter')),
            ],
            options={
                'verbose_name': 'Water Balance Rule',
                'verbose_name_plural': 'Water Balance Rules',
                'ordering': ['balance_model', 'priority', 'production_site__name', 'route_name'],
            },
        ),
        migrations.AddIndex(
            model_name='waterbalancemodel',
            index=models.Index(fields=['zone', 'is_active'], name='water_balan_zone_id_46ca68_idx'),
        ),
        migrations.AddIndex(
            model_name='waterbalancemodel',
            index=models.Index(fields=['effective_start_date', 'effective_end_date'], name='water_balan_effecti_490579_idx'),
        ),
        migrations.AddIndex(
            model_name='waterbalancenode',
            index=models.Index(fields=['code'], name='water_balan_code_d5732d_idx'),
        ),
        migrations.AddIndex(
            model_name='waterbalancenode',
            index=models.Index(fields=['node_type', 'is_active'], name='water_balan_node_ty_a4fbaf_idx'),
        ),
        migrations.AddIndex(
            model_name='waterbalancenodeinput',
            index=models.Index(fields=['node', 'is_active'], name='water_balan_node_id_ad0817_idx'),
        ),
        migrations.AddIndex(
            model_name='waterbalancenodeinput',
            index=models.Index(fields=['input_method', 'is_active'], name='water_balan_input_m_868b59_idx'),
        ),
        migrations.AddIndex(
            model_name='waterbalancenodeinput',
            index=models.Index(fields=['effective_start_date', 'effective_end_date'], name='water_balan_effecti_037505_idx'),
        ),
        migrations.AddIndex(
            model_name='waterbalancerule',
            index=models.Index(fields=['balance_model', 'is_active'], name='water_balan_balance_cdbc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='waterbalancerule',
            index=models.Index(fields=['method', 'is_active'], name='water_balan_method_e3d6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='waterbalancerule',
            index=models.Index(fields=['mixing_node', 'is_active'], name='water_balan_mixing__03fb8d_idx'),
        ),
        migrations.AddIndex(
            model_name='waterbalancerule',
            index=models.Index(fields=['effective_start_date', 'effective_end_date'], name='water_balan_effecti_13d945_idx'),
        ),
    ]
