# Generated by Django 6.0 on 2026-04-29 12:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0009_commercialdashboardreport_and_more'),
        ('production', '0008_productionsite_production_equals_supply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('production', 'Production'), ('distribution', 'Distribution')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('reported_by', models.CharField(max_length=150)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in-progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=150)),
                ('resolved_by', models.CharField(blank=True, max_length=150)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('estimated_impact_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('customer_notifications_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL)),
                ('production_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='production.productionsite')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_incidents', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='distribution.zone')),
            ],
            options={
                'ordering': ['-reported_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('status_from', models.CharField(blank=True, max_length=20)),
                ('status_to', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_comments', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_type', 'status'], name='incidents_i_inciden_b0a029_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['priority', 'status'], name='incidents_i_priorit_23fe56_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['reported_at'], name='incidents_i_reporte_fa94a0_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['zone', 'status'], name='incidents_i_zone_id_390d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['production_site', 'status'], name='incidents_i_product_7770f7_idx'),
        ),
    ]
