# Generated by Django 6.0 on 2026-03-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='meter_type',
            field=models.CharField(choices=[('WATER', 'Water Meter'), ('POWER_GRID', 'Grid Power Meter'), ('POWER_SOLAR', 'Solar Power Meter'), ('SUPPLY', 'Supply/Output Meter')], max_length=20),
        ),
    ]
