# Generated by Django 6.0 on 2026-03-31 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_add_supply_meter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='production.meter'),
        ),
    ]
