# Generated by Django 6.0 on 2026-03-31 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_meter_reading_set_null_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontarget',
            name='water_supply_target_m3',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Target water volume supplied (abstracted minus production loss)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='CompanyMonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('target_power_costs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_repair_maintenance_costs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_abstraction_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_chemical_costs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_total_direct_costs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_power_cost_per_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_power_cost_per_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_total_cost_per_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_costs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('repair_maintenance_costs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('abstraction_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('chemical_costs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_direct_costs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('power_cost_per_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_cost_per_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost_per_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('central_opening_date', models.DateField(blank=True, null=True)),
                ('central_closing_date', models.DateField(blank=True, null=True)),
                ('central_production_loss_m3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('central_available_for_sale_m3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('southern_opening_date', models.DateField(blank=True, null=True)),
                ('southern_closing_date', models.DateField(blank=True, null=True)),
                ('southern_production_loss_m3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('southern_available_for_sale_m3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('eastern_opening_date', models.DateField(blank=True, null=True)),
                ('eastern_closing_date', models.DateField(blank=True, null=True)),
                ('eastern_production_loss_m3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('eastern_available_for_sale_m3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_chemical_tests_production', models.IntegerField(default=0)),
                ('target_biological_tests_production', models.IntegerField(default=0)),
                ('target_chemical_tests_consumer', models.IntegerField(default=0)),
                ('target_biological_tests_consumer', models.IntegerField(default=0)),
                ('chemical_tests_production', models.IntegerField(default=0)),
                ('biological_tests_production', models.IntegerField(default=0)),
                ('chemical_tests_consumer', models.IntegerField(default=0)),
                ('biological_tests_consumer', models.IntegerField(default=0)),
                ('who_compliance_chemical_production', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('who_compliance_biological_production', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('who_compliance_chemical_consumer', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('who_compliance_biological_consumer', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_finalized', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company monthly summary',
                'verbose_name_plural': 'Company monthly summaries',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month'], name='production__year_e0752e_idx')],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
