# Generated by Django 6.0 on 2026-04-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_add_company_summary_and_supply_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='water_received_m3',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Water received from another production site; derived for Water Works', max_digits=15),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='water_supplied_m3',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total water supplied from site output meters', max_digits=15),
        ),
        migrations.AddField(
            model_name='monthlyproduction',
            name='water_received_m3',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Water received from another production site; derived for Water Works', max_digits=15),
        ),
        migrations.AddField(
            model_name='monthlyproduction',
            name='water_supplied_m3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
