# Generated by Django 6.0 on 2026-04-15 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_dailyproduction_water_received_m3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Production Cost Config', max_length=100)),
                ('grid_power_cost_per_kwh', models.DecimalField(decimal_places=2, default=0, help_text='Tariff applied to grid power consumption.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('solar_power_cost_per_kwh', models.DecimalField(decimal_places=2, default=0, help_text='Tariff applied to solar power consumption.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Cost Configuration',
                'verbose_name_plural': 'Production Cost Configurations',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
