# Generated by Django 6.0 on 2026-04-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_productioncostconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyproduction',
            name='closing_date',
            field=models.DateField(blank=True, help_text='Calendar month end date for this period', null=True),
        ),
        migrations.AlterField(
            model_name='monthlyproduction',
            name='start_date',
            field=models.DateField(blank=True, help_text='Calendar month start date for this period', null=True),
        ),
    ]
