# Generated by Django 6.0 on 2026-04-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_monthlyproduction_closing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsite',
            name='production_equals_supply',
            field=models.BooleanField(default=False, help_text="Enable when the same production or borehole meter reading should also be treated as the site's supply volume."),
        ),
    ]
