# Generated by Django 6.0 on 2026-04-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_meter_reading_set_null_on_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributionregion',
            options={'ordering': ['dashboard_order', 'name'], 'verbose_name': 'Distribution Region', 'verbose_name_plural': 'Distribution Regions'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['region__dashboard_order', 'dashboard_order', 'name'], 'verbose_name': 'Distribution Zone', 'verbose_name_plural': 'Distribution Zones'},
        ),
        migrations.AddField(
            model_name='distributionregion',
            name='dashboard_billed_kpi_code',
            field=models.CharField(blank=True, help_text='Workbook KPI code for regional billed volume', max_length=20),
        ),
        migrations.AddField(
            model_name='distributionregion',
            name='dashboard_nrw_m3_kpi_code',
            field=models.CharField(blank=True, help_text='Workbook KPI code for regional NRW volume', max_length=20),
        ),
        migrations.AddField(
            model_name='distributionregion',
            name='dashboard_nrw_pct_kpi_code',
            field=models.CharField(blank=True, help_text='Workbook KPI code for regional NRW percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='distributionregion',
            name='dashboard_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in the distribution dashboard'),
        ),
        migrations.AddField(
            model_name='distributionregion',
            name='dashboard_supply_kpi_code',
            field=models.CharField(blank=True, help_text='Workbook KPI code for regional supplied volume', max_length=20),
        ),
        migrations.AddField(
            model_name='zone',
            name='dashboard_billed_kpi_code',
            field=models.CharField(blank=True, help_text='Workbook KPI code for billed volume', max_length=20),
        ),
        migrations.AddField(
            model_name='zone',
            name='dashboard_nrw_pct_kpi_code',
            field=models.CharField(blank=True, help_text='Workbook KPI code for NRW percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='zone',
            name='dashboard_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in the distribution dashboard'),
        ),
        migrations.AddField(
            model_name='zone',
            name='dashboard_supply_kpi_code',
            field=models.CharField(blank=True, help_text='Workbook KPI code for supplied volume', max_length=20),
        ),
        migrations.AddField(
            model_name='zone',
            name='supply_aggregation_method',
            field=models.CharField(choices=[('UNSET', 'Not Configured'), ('ZONE_METER', 'Zone Master Meter'), ('DMA_SUM', 'Sum of DMA Inlets')], default='UNSET', help_text="How this zone's official supplied volume should be calculated", max_length=20),
        ),
    ]
