# Generated by Django 6.0 on 2026-04-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_alter_distributionregion_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneSupplyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation_method', models.CharField(choices=[('ONE_METER', 'One Meter'), ('SUM_OF_DMA_METERS', 'Sum of DMA Meters'), ('SUM_OF_SELECTED_METERS', 'Sum of Selected Meters')], default='ONE_METER', max_length=30)),
                ('infrastructure_description', models.TextField(blank=True, help_text='Plain-language description of how the zone is supplied.')),
                ('calculation_notes', models.TextField(blank=True, help_text='Additional calculation assumptions or exclusions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_dmas', models.ManyToManyField(blank=True, help_text='DMAs whose inlet meters should be summed for zonal supply.', related_name='zone_supply_configurations', to='distribution.dma')),
                ('component_meters', models.ManyToManyField(blank=True, help_text='Explicit meters to sum when the zone is composed from selected meters.', related_name='component_for_zone_supply_configs', to='distribution.distributionmeter')),
                ('primary_meter', models.ForeignKey(blank=True, help_text='Official zone supply meter when the zone is defined by one meter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_zone_supply_configs', to='distribution.distributionmeter')),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_configuration', to='distribution.zone')),
            ],
            options={
                'verbose_name': 'Zone Supply Configuration',
                'verbose_name_plural': 'Zone Supply Configurations',
            },
        ),
    ]
