# Generated by Django 6.0 on 2026-04-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_zonesupplyconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbillingdata',
            name='sewer_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='customerbillingdata',
            name='water_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='globalnrwperformance',
            name='active_sewer_connections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalnrwperformance',
            name='active_water_connections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalnrwperformance',
            name='inactive_sewer_connections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalnrwperformance',
            name='inactive_water_connections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalnrwperformance',
            name='maintenance_repair_operational_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='globalnrwperformance',
            name='total_connections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regionaldistribution',
            name='active_sewer_connections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regionaldistribution',
            name='active_water_connections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regionaldistribution',
            name='amount_billed_sewer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='regionaldistribution',
            name='amount_billed_water',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
