# Generated by Django 6.0 on 2026-04-20 14:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_customerbillingdata_sewer_revenue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneBillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('opening_date', models.DateField(help_text='Meter opening date for this zonal cycle')),
                ('closing_date', models.DateField(help_text='Meter closing date for this zonal cycle')),
                ('is_finalized', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='distribution.zone')),
            ],
            options={
                'verbose_name': 'Zone Billing Cycle',
                'verbose_name_plural': 'Zone Billing Cycles',
                'ordering': ['-year', '-month', 'zone'],
                'indexes': [models.Index(fields=['year', 'month'], name='distributio_year_a954bd_idx'), models.Index(fields=['zone', 'year', 'month'], name='distributio_zone_id_ed0c8a_idx')],
                'unique_together': {('zone', 'year', 'month')},
            },
        ),
    ]
