# Generated by Django 6.0 on 2026-04-23 06:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0006_zonebillingcycle'),
        ('production', '0007_alter_monthlyproduction_closing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbillingdata',
            name='zone_billing_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_billing_data', to='distribution.zonebillingcycle'),
        ),
        migrations.AddField(
            model_name='monthlydistribution',
            name='zone_billing_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_distribution', to='distribution.zonebillingcycle'),
        ),
        migrations.CreateModel(
            name='OperationalMonthlyDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('volume_supplied_m3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('volume_supplied_target_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('volume_supplied_realization_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_monthly_distribution', to='distribution.zone')),
            ],
            options={
                'verbose_name': 'Operational Monthly Distribution',
                'verbose_name_plural': 'Operational Monthly Distribution',
                'ordering': ['-year', '-month', 'zone'],
                'indexes': [models.Index(fields=['zone', 'year', 'month'], name='distributio_zone_id_ecefe1_idx'), models.Index(fields=['year', 'month'], name='distributio_year_5d02ea_idx')],
                'unique_together': {('zone', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='OperationalRegionalDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('volume_supplied_m3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('volume_supplied_target_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('volume_supplied_realization_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_distribution', to='distribution.distributionregion')),
            ],
            options={
                'verbose_name': 'Operational Regional Distribution',
                'verbose_name_plural': 'Operational Regional Distribution',
                'ordering': ['-year', '-month', 'region'],
                'indexes': [models.Index(fields=['region', 'year', 'month'], name='distributio_region__37627b_idx'), models.Index(fields=['year', 'month'], name='distributio_year_8f210c_idx')],
                'unique_together': {('region', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='OperationalTransmissionLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('water_available_from_production_m3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('water_available_to_distribution_m3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transmission_loss_m3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transmission_loss_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_transmission_losses', to='production.region')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_transmission_losses', to='distribution.distributionregion')),
            ],
            options={
                'verbose_name': 'Operational Transmission Loss',
                'verbose_name_plural': 'Operational Transmission Loss',
                'ordering': ['-year', '-month', 'region'],
                'indexes': [models.Index(fields=['region', 'year', 'month'], name='distributio_region__6b11bb_idx'), models.Index(fields=['year', 'month'], name='distributio_year_bea47d_idx')],
                'unique_together': {('region', 'year', 'month')},
            },
        ),
    ]
