# Generated by Django 6.0 on 2026-04-23 09:21

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_zone_supply_meter_links(apps, schema_editor):
    ZoneSupplyConfiguration = apps.get_model('distribution', 'ZoneSupplyConfiguration')
    WaterMeter = apps.get_model('metering', 'WaterMeter')

    for config in ZoneSupplyConfiguration.objects.all():
        changed = []
        if config.primary_meter_id and config.primary_water_meter_id is None:
            legacy_meter_number = config.primary_meter.meter_number
            shared_meter = WaterMeter.objects.filter(meter_number=legacy_meter_number).first()
            if shared_meter:
                config.primary_water_meter_id = shared_meter.id
                changed.append('primary_water_meter')
        if changed:
            config.save(update_fields=changed)

        if config.component_meters.exists():
            meter_numbers = list(config.component_meters.values_list('meter_number', flat=True))
            shared_ids = list(WaterMeter.objects.filter(meter_number__in=meter_numbers).values_list('id', flat=True))
            if shared_ids:
                config.component_water_meters.set(shared_ids)


def reverse_copy_legacy_zone_supply_meter_links(apps, schema_editor):
    ZoneSupplyConfiguration = apps.get_model('distribution', 'ZoneSupplyConfiguration')
    for config in ZoneSupplyConfiguration.objects.all():
        config.component_water_meters.clear()
        if config.primary_water_meter_id is not None:
            config.primary_water_meter_id = None
            config.save(update_fields=['primary_water_meter'])


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_customerbillingdata_zone_billing_cycle_and_more'),
        ('metering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonesupplyconfiguration',
            name='component_water_meters',
            field=models.ManyToManyField(blank=True, help_text='Shared water meters to sum when the zone is composed from selected meters.', related_name='component_for_zone_supply_configs', to='metering.watermeter'),
        ),
        migrations.AddField(
            model_name='zonesupplyconfiguration',
            name='primary_water_meter',
            field=models.ForeignKey(blank=True, help_text='Official shared water meter for a one-meter zone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_zone_supply_configs', to='metering.watermeter'),
        ),
        migrations.RunPython(copy_legacy_zone_supply_meter_links, reverse_copy_legacy_zone_supply_meter_links),
    ]
