# Generated by Django 6.0 on 2026-04-27 12:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0008_zonesupplyconfiguration_component_water_meters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialDashboardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sales & CC Dashboard', max_length=200)),
                ('fiscal_year_start', models.IntegerField(help_text='Financial year start year. Example: 2025 for FY 2025-26.')),
                ('fiscal_year_label', models.CharField(max_length=20, unique=True)),
                ('current_snapshot_date', models.DateField(blank=True, null=True)),
                ('current_fiscal_month_index', models.IntegerField(blank=True, help_text='Jul=1 through Jun=12 position from the workbook General sheet.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('sewerage_percentage_of_water', models.DecimalField(decimal_places=4, default=0, help_text='General workbook parameter used by the commercial dashboard.', max_digits=8)),
                ('source_workbook', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commercial Dashboard Report',
                'verbose_name_plural': 'Commercial Dashboard Reports',
                'ordering': ['-fiscal_year_start'],
            },
        ),
        migrations.AlterField(
            model_name='zonesupplyconfiguration',
            name='aggregation_method',
            field=models.CharField(choices=[('ONE_METER', 'One Meter'), ('SUM_OF_DMA_METERS', 'Sum of DMA Meters'), ('SUM_OF_SELECTED_METERS', 'Sum of Selected Meters'), ('CUSTOM_ASSIGNMENTS', 'Custom Assignment Set')], default='ONE_METER', max_length=30),
        ),
        migrations.CreateModel(
            name='CommercialDashboardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('workbook_row', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='distribution.commercialdashboardreport')),
            ],
            options={
                'verbose_name': 'Commercial Dashboard Section',
                'verbose_name_plural': 'Commercial Dashboard Sections',
                'ordering': ['display_order', 'id'],
                'unique_together': {('report', 'title')},
            },
        ),
        migrations.CreateModel(
            name='CommercialDashboardKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('item_number', models.CharField(blank=True, max_length=20)),
                ('subgroup_title', models.CharField(blank=True, help_text='Optional workbook subgroup header such as Eastern Region.', max_length=120)),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global'), ('REGION', 'Region'), ('ZONE', 'Zone'), ('CUSTOM', 'Custom')], default='GLOBAL', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('workbook_row', models.PositiveIntegerField(blank=True, null=True)),
                ('is_total', models.BooleanField(default=False)),
                ('is_summary', models.BooleanField(default=False)),
                ('is_percentage', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_kpis', to='distribution.distributionregion')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_kpis', to='distribution.zone')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='distribution.commercialdashboardreport')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='distribution.commercialdashboardsection')),
            ],
            options={
                'verbose_name': 'Commercial Dashboard KPI',
                'verbose_name_plural': 'Commercial Dashboard KPIs',
                'ordering': ['display_order', 'id'],
                'unique_together': {('report', 'display_order')},
            },
        ),
        migrations.CreateModel(
            name='CommercialDashboardMonthlyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('target_value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('target_value_text', models.CharField(blank=True, max_length=255)),
                ('actual_value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('actual_value_text', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_values', to='distribution.commercialdashboardkpi')),
            ],
            options={
                'verbose_name': 'Commercial Dashboard Monthly Value',
                'verbose_name_plural': 'Commercial Dashboard Monthly Values',
                'ordering': ['month', 'kpi__display_order'],
                'unique_together': {('kpi', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CommercialDashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_year', models.IntegerField()),
                ('snapshot_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('monthly_target_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('monthly_target_text', models.CharField(blank=True, max_length=255)),
                ('monthly_actual_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('monthly_actual_text', models.CharField(blank=True, max_length=255)),
                ('monthly_realization_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('cumulative_target_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cumulative_target_text', models.CharField(blank=True, max_length=255)),
                ('cumulative_actual_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cumulative_actual_text', models.CharField(blank=True, max_length=255)),
                ('cumulative_realization_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='distribution.commercialdashboardkpi')),
            ],
            options={
                'verbose_name': 'Commercial Dashboard Snapshot',
                'verbose_name_plural': 'Commercial Dashboard Snapshots',
                'ordering': ['snapshot_year', 'snapshot_month', 'kpi__display_order'],
                'unique_together': {('kpi', 'snapshot_year', 'snapshot_month')},
            },
        ),
    ]
