# Generated by Django 6.0 on 2026-05-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0009_commercialdashboardreport_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operationalmonthlydistribution',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='operationalmonthlydistribution',
            name='distributio_zone_id_ecefe1_idx',
        ),
        migrations.RemoveIndex(
            model_name='operationalmonthlydistribution',
            name='distributio_year_5d02ea_idx',
        ),
        migrations.AlterUniqueTogether(
            name='operationalregionaldistribution',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='operationalregionaldistribution',
            name='distributio_region__37627b_idx',
        ),
        migrations.RemoveIndex(
            model_name='operationalregionaldistribution',
            name='distributio_year_8f210c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='operationaltransmissionloss',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='operationaltransmissionloss',
            name='distributio_region__6b11bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='operationaltransmissionloss',
            name='distributio_year_bea47d_idx',
        ),
        migrations.RemoveField(
            model_name='operationalregionaldistribution',
            name='region',
        ),
        migrations.RemoveField(
            model_name='operationaltransmissionloss',
            name='production_region',
        ),
        migrations.RemoveField(
            model_name='operationaltransmissionloss',
            name='region',
        ),
        migrations.DeleteModel(
            name='OperationalMonthlyDistribution',
        ),
        migrations.DeleteModel(
            name='OperationalRegionalDistribution',
        ),
        migrations.DeleteModel(
            name='OperationalTransmissionLoss',
        ),
    ]
