# Generated by Django 6.0 on 2026-04-23 09:21

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _merge_notes(existing, new_note):
    existing = (existing or '').strip()
    new_note = (new_note or '').strip()
    if not new_note:
        return existing
    if not existing:
        return new_note
    if new_note in existing:
        return existing
    return f'{existing}\n{new_note}'


def _update_if_empty(instance, field, value):
    current = getattr(instance, field)
    if field == 'notes':
        merged = _merge_notes(current, value)
        if merged != current:
            setattr(instance, field, merged)
            return True
        return False
    if field == 'is_active':
        if current != value:
            setattr(instance, field, value)
            return True
        return False
    if current in (None, '', 0) and value not in (None, ''):
        setattr(instance, field, value)
        return True
    return False


def backfill_shared_metering(apps, schema_editor):
    ProductionMeter = apps.get_model('production', 'Meter')
    ProductionMeterReading = apps.get_model('production', 'MeterReading')
    DistributionMeter = apps.get_model('distribution', 'DistributionMeter')
    DistributionMeterReading = apps.get_model('distribution', 'DistributionMeterReading')

    WaterMeter = apps.get_model('metering', 'WaterMeter')
    EnergyMeter = apps.get_model('metering', 'EnergyMeter')
    WaterMeterReading = apps.get_model('metering', 'WaterMeterReading')
    EnergyMeterReading = apps.get_model('metering', 'EnergyMeterReading')
    ProductionWaterMeterAssignment = apps.get_model('metering', 'ProductionWaterMeterAssignment')
    ProductionEnergyMeterAssignment = apps.get_model('metering', 'ProductionEnergyMeterAssignment')
    DistributionWaterMeterAssignment = apps.get_model('metering', 'DistributionWaterMeterAssignment')

    production_water_map = {}
    production_energy_map = {}
    distribution_water_map = {}

    for legacy in ProductionMeter.objects.all().order_by('id'):
        note = f'Imported from production meter #{legacy.id}. {legacy.notes or ""}'.strip()
        if legacy.meter_type in {'WATER', 'SUPPLY'}:
            water_meter, created = WaterMeter.objects.get_or_create(
                meter_number=legacy.meter_number,
                defaults={
                    'manufacturer': legacy.manufacturer,
                    'model': legacy.model,
                    'capacity': legacy.capacity,
                    'is_active': legacy.is_active,
                    'installation_date': legacy.installation_date or datetime.date.today(),
                    'last_calibration_date': legacy.last_calibration_date,
                    'next_calibration_date': legacy.next_calibration_date,
                    'initial_reading': legacy.initial_reading,
                    'notes': note,
                },
            )
            if not created:
                updated = []
                for field, value in {
                    'manufacturer': legacy.manufacturer,
                    'model': legacy.model,
                    'capacity': legacy.capacity,
                    'is_active': legacy.is_active,
                    'installation_date': legacy.installation_date,
                    'last_calibration_date': legacy.last_calibration_date,
                    'next_calibration_date': legacy.next_calibration_date,
                    'initial_reading': legacy.initial_reading,
                    'notes': note,
                }.items():
                    if _update_if_empty(water_meter, field, value):
                        updated.append(field)
                if updated:
                    water_meter.save(update_fields=updated + ['updated_at'])

            role = 'ABSTRACTION' if legacy.meter_type == 'WATER' else 'SUPPLY'
            assignment, _ = ProductionWaterMeterAssignment.objects.update_or_create(
                legacy_production_meter_id=legacy.id,
                defaults={
                    'water_meter_id': water_meter.id,
                    'production_site_id': legacy.production_site_id,
                    'water_source_id': legacy.water_source_id if role == 'ABSTRACTION' else None,
                    'assignment_role': role,
                    'is_active': legacy.is_active,
                    'start_date': legacy.installation_date,
                    'notes': note,
                },
            )
            production_water_map[legacy.id] = assignment.water_meter_id
            continue

        energy_kind = 'GRID' if legacy.meter_type == 'POWER_GRID' else 'SOLAR'
        energy_meter, created = EnergyMeter.objects.get_or_create(
            meter_number=legacy.meter_number,
            defaults={
                'energy_kind': energy_kind,
                'manufacturer': legacy.manufacturer,
                'model': legacy.model,
                'capacity': legacy.capacity,
                'is_active': legacy.is_active,
                'installation_date': legacy.installation_date or datetime.date.today(),
                'last_calibration_date': legacy.last_calibration_date,
                'next_calibration_date': legacy.next_calibration_date,
                'initial_reading': legacy.initial_reading,
                'notes': note,
            },
        )
        if not created:
            updated = []
            for field, value in {
                'manufacturer': legacy.manufacturer,
                'model': legacy.model,
                'capacity': legacy.capacity,
                'is_active': legacy.is_active,
                'installation_date': legacy.installation_date,
                'last_calibration_date': legacy.last_calibration_date,
                'next_calibration_date': legacy.next_calibration_date,
                'initial_reading': legacy.initial_reading,
                'notes': note,
            }.items():
                if _update_if_empty(energy_meter, field, value):
                    updated.append(field)
            if updated:
                energy_meter.save(update_fields=updated + ['updated_at'])

        assignment, _ = ProductionEnergyMeterAssignment.objects.update_or_create(
            legacy_production_meter_id=legacy.id,
            defaults={
                'energy_meter_id': energy_meter.id,
                'production_site_id': legacy.production_site_id,
                'assignment_role': energy_kind,
                'is_active': legacy.is_active,
                'start_date': legacy.installation_date,
                'notes': note,
            },
        )
        production_energy_map[legacy.id] = assignment.energy_meter_id

    for legacy in DistributionMeter.objects.all().order_by('id'):
        note = f'Imported from distribution meter #{legacy.id}. {legacy.notes or ""}'.strip()
        water_meter, created = WaterMeter.objects.get_or_create(
            meter_number=legacy.meter_number,
            defaults={
                'manufacturer': legacy.manufacturer,
                'model': legacy.model,
                'diameter_mm': legacy.diameter_mm,
                'is_active': legacy.is_active,
                'installation_date': legacy.installation_date or datetime.date.today(),
                'last_calibration_date': legacy.last_calibration_date,
                'next_calibration_date': legacy.next_calibration_date,
                'initial_reading': legacy.initial_reading,
                'notes': note,
            },
        )
        if not created:
            updated = []
            for field, value in {
                'manufacturer': legacy.manufacturer,
                'model': legacy.model,
                'diameter_mm': legacy.diameter_mm,
                'is_active': legacy.is_active,
                'installation_date': legacy.installation_date,
                'last_calibration_date': legacy.last_calibration_date,
                'next_calibration_date': legacy.next_calibration_date,
                'initial_reading': legacy.initial_reading,
                'notes': note,
            }.items():
                if _update_if_empty(water_meter, field, value):
                    updated.append(field)
            if updated:
                water_meter.save(update_fields=updated + ['updated_at'])

        assignment, _ = DistributionWaterMeterAssignment.objects.update_or_create(
            legacy_distribution_meter_id=legacy.id,
            defaults={
                'water_meter_id': water_meter.id,
                'zone_id': legacy.zone_id,
                'dma_id': legacy.dma_id,
                'assignment_role': legacy.meter_location_type,
                'allocation_percentage': 100,
                'is_active': legacy.is_active,
                'start_date': legacy.installation_date,
                'notes': note,
            },
        )
        distribution_water_map[legacy.id] = assignment.water_meter_id

    for legacy in ProductionMeterReading.objects.select_related('meter').order_by('reading_date', 'reading_time', 'id'):
        if legacy.meter_id is None:
            continue
        if legacy.meter.meter_type in {'WATER', 'SUPPLY'}:
            water_meter_id = production_water_map.get(legacy.meter_id)
            if not water_meter_id:
                continue
            reading, created = WaterMeterReading.objects.get_or_create(
                water_meter_id=water_meter_id,
                reading_date=legacy.reading_date,
                defaults={
                    'reading_time': legacy.reading_time,
                    'current_reading': legacy.current_reading,
                    'previous_reading': legacy.previous_reading,
                    'consumption': legacy.consumption,
                    'read_by': legacy.read_by,
                    'reading_method': legacy.reading_method,
                    'is_validated': legacy.is_validated,
                    'is_anomaly': legacy.is_anomaly,
                    'validated_by': legacy.validated_by,
                    'validated_at': legacy.validated_at,
                    'legacy_production_meter_reading_id': legacy.id,
                    'notes': legacy.notes,
                },
            )
            if not created and reading.legacy_production_meter_reading_id is None:
                reading.legacy_production_meter_reading_id = legacy.id
                reading.is_validated = reading.is_validated or legacy.is_validated
                reading.is_anomaly = reading.is_anomaly or legacy.is_anomaly
                reading.notes = _merge_notes(reading.notes, legacy.notes)
                reading.save(update_fields=[
                    'legacy_production_meter_reading_id', 'is_validated', 'is_anomaly', 'notes', 'updated_at'
                ])
            continue

        energy_meter_id = production_energy_map.get(legacy.meter_id)
        if not energy_meter_id:
            continue
        reading, created = EnergyMeterReading.objects.get_or_create(
            energy_meter_id=energy_meter_id,
            reading_date=legacy.reading_date,
            defaults={
                'reading_time': legacy.reading_time,
                'current_reading': legacy.current_reading,
                'previous_reading': legacy.previous_reading,
                'consumption': legacy.consumption,
                'read_by': legacy.read_by,
                'reading_method': legacy.reading_method,
                'is_validated': legacy.is_validated,
                'is_anomaly': legacy.is_anomaly,
                'validated_by': legacy.validated_by,
                'validated_at': legacy.validated_at,
                'legacy_production_meter_reading_id': legacy.id,
                'notes': legacy.notes,
            },
        )
        if not created and reading.legacy_production_meter_reading_id is None:
            reading.legacy_production_meter_reading_id = legacy.id
            reading.is_validated = reading.is_validated or legacy.is_validated
            reading.is_anomaly = reading.is_anomaly or legacy.is_anomaly
            reading.notes = _merge_notes(reading.notes, legacy.notes)
            reading.save(update_fields=[
                'legacy_production_meter_reading_id', 'is_validated', 'is_anomaly', 'notes', 'updated_at'
            ])

    for legacy in DistributionMeterReading.objects.select_related('meter').order_by('reading_date', 'reading_time', 'id'):
        if legacy.meter_id is None:
            continue
        water_meter_id = distribution_water_map.get(legacy.meter_id)
        if not water_meter_id:
            continue
        reading, created = WaterMeterReading.objects.get_or_create(
            water_meter_id=water_meter_id,
            reading_date=legacy.reading_date,
            defaults={
                'reading_time': legacy.reading_time,
                'current_reading': legacy.current_reading,
                'previous_reading': legacy.previous_reading,
                'consumption': legacy.volume_supplied,
                'read_by': legacy.read_by,
                'reading_method': legacy.reading_method,
                'is_validated': legacy.is_validated,
                'is_anomaly': legacy.is_anomaly,
                'validated_by': legacy.validated_by,
                'validated_at': legacy.validated_at,
                'legacy_distribution_meter_reading_id': legacy.id,
                'notes': legacy.notes,
            },
        )
        if not created and reading.legacy_distribution_meter_reading_id is None:
            reading.legacy_distribution_meter_reading_id = legacy.id
            reading.is_validated = reading.is_validated or legacy.is_validated
            reading.is_anomaly = reading.is_anomaly or legacy.is_anomaly
            reading.notes = _merge_notes(reading.notes, legacy.notes)
            reading.save(update_fields=[
                'legacy_distribution_meter_reading_id', 'is_validated', 'is_anomaly', 'notes', 'updated_at'
            ])


def reverse_backfill_shared_metering(apps, schema_editor):
    apps.get_model('metering', 'WaterMeterReading').objects.all().delete()
    apps.get_model('metering', 'EnergyMeterReading').objects.all().delete()
    apps.get_model('metering', 'DistributionWaterMeterAssignment').objects.all().delete()
    apps.get_model('metering', 'ProductionWaterMeterAssignment').objects.all().delete()
    apps.get_model('metering', 'ProductionEnergyMeterAssignment').objects.all().delete()
    apps.get_model('metering', 'WaterMeter').objects.all().delete()
    apps.get_model('metering', 'EnergyMeter').objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0007_customerbillingdata_zone_billing_cycle_and_more'),
        ('production', '0008_productionsite_production_equals_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=100, unique=True)),
                ('energy_kind', models.CharField(choices=[('GRID', 'Grid Power'), ('SOLAR', 'Solar Power')], max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum reading capacity where available.', max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('installation_date', models.DateField()),
                ('last_calibration_date', models.DateField(blank=True, null=True)),
                ('next_calibration_date', models.DateField(blank=True, null=True)),
                ('initial_reading', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Energy Meter',
                'verbose_name_plural': 'Energy Meters',
                'ordering': ['meter_number'],
            },
        ),
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('diameter_mm', models.IntegerField(blank=True, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum reading capacity where available.', max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('installation_date', models.DateField()),
                ('last_calibration_date', models.DateField(blank=True, null=True)),
                ('next_calibration_date', models.DateField(blank=True, null=True)),
                ('initial_reading', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Water Meter',
                'verbose_name_plural': 'Water Meters',
                'ordering': ['meter_number'],
            },
        ),
        migrations.CreateModel(
            name='DistributionWaterMeterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_role', models.CharField(choices=[('ZONE_INLET', 'Zone Inlet'), ('DMA_INLET', 'DMA Inlet'), ('BULK_SUPPLY', 'Bulk Supply Point'), ('TRANSMISSION', 'Transmission Line')], max_length=20)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, default=100, help_text='Optional contribution factor when one physical meter is shared.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('legacy_distribution_meter_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_meter_assignments', to='distribution.dma')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_meter_assignments', to='distribution.zone')),
                ('water_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_assignments', to='metering.watermeter')),
            ],
            options={
                'verbose_name': 'Distribution Water Meter Assignment',
                'verbose_name_plural': 'Distribution Water Meter Assignments',
                'ordering': ['zone__name', 'dma__name', 'water_meter__meter_number'],
            },
        ),
        migrations.CreateModel(
            name='EnergyMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('reading_time', models.TimeField(default=django.utils.timezone.now)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('previous_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('read_by', models.CharField(blank=True, max_length=200)),
                ('reading_method', models.CharField(choices=[('MANUAL', 'Manual Reading'), ('AUTOMATED', 'Automated'), ('SCADA', 'SCADA/Automated'), ('ESTIMATED', 'Estimated')], default='MANUAL', max_length=50)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('validated_by', models.CharField(blank=True, max_length=200)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_production_meter_reading_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('energy_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='metering.energymeter')),
            ],
            options={
                'verbose_name': 'Energy Meter Reading',
                'verbose_name_plural': 'Energy Meter Readings',
                'ordering': ['-reading_date', '-reading_time', 'energy_meter__meter_number'],
                'indexes': [models.Index(fields=['energy_meter', '-reading_date'], name='metering_en_energy__8d66fd_idx'), models.Index(fields=['reading_date'], name='metering_en_reading_8fa506_idx')],
                'unique_together': {('energy_meter', 'reading_date')},
            },
        ),
        migrations.CreateModel(
            name='ProductionEnergyMeterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_role', models.CharField(choices=[('GRID', 'Grid Power'), ('SOLAR', 'Solar Power')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('legacy_production_meter_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('energy_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_assignments', to='metering.energymeter')),
                ('production_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_meter_assignments', to='production.productionsite')),
            ],
            options={
                'verbose_name': 'Production Energy Meter Assignment',
                'verbose_name_plural': 'Production Energy Meter Assignments',
                'ordering': ['production_site__name', 'assignment_role', 'energy_meter__meter_number'],
                'unique_together': {('energy_meter', 'production_site', 'assignment_role')},
            },
        ),
        migrations.CreateModel(
            name='ProductionWaterMeterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_role', models.CharField(choices=[('ABSTRACTION', 'Production / Abstraction'), ('SUPPLY', 'Supply / Output')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('legacy_production_meter_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_meter_assignments', to='production.productionsite')),
                ('water_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_assignments', to='production.watersource')),
                ('water_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_assignments', to='metering.watermeter')),
            ],
            options={
                'verbose_name': 'Production Water Meter Assignment',
                'verbose_name_plural': 'Production Water Meter Assignments',
                'ordering': ['production_site__name', 'assignment_role', 'water_meter__meter_number'],
                'unique_together': {('water_meter', 'production_site', 'water_source', 'assignment_role')},
            },
        ),
        migrations.CreateModel(
            name='WaterMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('reading_time', models.TimeField(default=django.utils.timezone.now)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('previous_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('read_by', models.CharField(blank=True, max_length=200)),
                ('reading_method', models.CharField(choices=[('MANUAL', 'Manual Reading'), ('AUTOMATED', 'Automated'), ('SCADA', 'SCADA/Automated'), ('ESTIMATED', 'Estimated')], default='MANUAL', max_length=50)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('validated_by', models.CharField(blank=True, max_length=200)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_production_meter_reading_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('legacy_distribution_meter_reading_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('water_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='metering.watermeter')),
            ],
            options={
                'verbose_name': 'Water Meter Reading',
                'verbose_name_plural': 'Water Meter Readings',
                'ordering': ['-reading_date', '-reading_time', 'water_meter__meter_number'],
                'indexes': [models.Index(fields=['water_meter', '-reading_date'], name='metering_wa_water_m_c03b1c_idx'), models.Index(fields=['reading_date'], name='metering_wa_reading_31f213_idx')],
                'unique_together': {('water_meter', 'reading_date')},
            },
        ),
        migrations.RunPython(backfill_shared_metering, reverse_backfill_shared_metering),
    ]
