# Generated by Django 6.0 on 2026-04-28 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_user_profiles(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    UserProfile = apps.get_model('metering', 'UserProfile')

    for user in User.objects.all():
        default_role = 'PRODUCTION_SUPERVISOR' if (user.is_staff or user.is_superuser) else 'PUMP_OPERATOR'
        UserProfile.objects.get_or_create(
            user=user,
            defaults={'role': default_role},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0009_commercialdashboardreport_and_more'),
        ('metering', '0003_meter_display_names'),
        ('production', '0008_productionsite_production_equals_supply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRODUCTION_SUPERVISOR', 'Production Supervisor'), ('PUMP_OPERATOR', 'Pump Operator'), ('ZONAL_OFFICER', 'Zonal Officer'), ('PLUMBER', 'Plumber')], max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metering_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='MeterReadingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('PRODUCTION_SITE', 'Production Site'), ('ZONE', 'Zone')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_reading_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_reading_assignments', to=settings.AUTH_USER_MODEL)),
                ('energy_meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_reading_assignments', to='metering.energymeter')),
                ('production_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_reading_assignments', to='production.productionsite')),
                ('water_meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_reading_assignments', to='metering.watermeter')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_reading_assignments', to='distribution.zone')),
            ],
            options={
                'verbose_name': 'Meter Reading Assignment',
                'verbose_name_plural': 'Meter Reading Assignments',
                'ordering': ['assignee__username', 'scope_type', 'production_site__name', 'zone__name'],
                'indexes': [models.Index(fields=['assignee', 'is_active'], name='metering_me_assigne_fcb360_idx'), models.Index(fields=['scope_type', 'is_active'], name='metering_me_scope_t_d0e24c_idx'), models.Index(fields=['water_meter', 'is_active'], name='metering_me_water_m_486c11_idx'), models.Index(fields=['energy_meter', 'is_active'], name='metering_me_energy__2307b0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('scope_type', 'PRODUCTION_SITE'), ('water_meter__isnull', False)), fields=('assignee', 'production_site', 'water_meter'), name='unique_user_production_water_reading_assignment'), models.UniqueConstraint(condition=models.Q(('energy_meter__isnull', False), ('scope_type', 'PRODUCTION_SITE')), fields=('assignee', 'production_site', 'energy_meter'), name='unique_user_production_energy_reading_assignment'), models.UniqueConstraint(condition=models.Q(('scope_type', 'ZONE'), ('water_meter__isnull', False)), fields=('assignee', 'zone', 'water_meter'), name='unique_user_zone_water_reading_assignment')],
            },
        ),
        migrations.RunPython(create_user_profiles, noop_reverse),
    ]
