# Generated by Django 6.0 on 2026-04-30 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fiscal_year_start', models.PositiveIntegerField()),
                ('fiscal_year_label', models.CharField(blank=True, max_length=20)),
                ('current_snapshot_date', models.DateField(blank=True, null=True)),
                ('current_fiscal_month_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_workbook', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fiscal_year_start', 'name'],
                'unique_together': {('name', 'fiscal_year_start')},
            },
        ),
        migrations.CreateModel(
            name='FinanceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='finance.financereport')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('report', 'title')},
            },
        ),
        migrations.CreateModel(
            name='FinanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('metric_kind', models.CharField(choices=[('MONEY', 'Money'), ('PERCENTAGE', 'Percentage'), ('COUNT', 'Count'), ('DATE', 'Date'), ('TEXT', 'Text')], default='MONEY', max_length=20)),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global'), ('REGION', 'Region'), ('CUSTOM', 'Custom')], default='GLOBAL', max_length=20)),
                ('scope_name', models.CharField(blank=True, max_length=100)),
                ('cumulative_behavior', models.CharField(choices=[('SUM', 'Sum'), ('AVERAGE', 'Average'), ('LAST_VALUE', 'Last Value')], default='SUM', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('workbook_sheet', models.CharField(blank=True, max_length=100)),
                ('workbook_row', models.PositiveIntegerField(blank=True, null=True)),
                ('is_total', models.BooleanField(default=False)),
                ('is_summary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='finance.financereport')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='finance.financesection')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('report', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FinanceMonthlyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('fiscal_month_index', models.PositiveSmallIntegerField()),
                ('target_value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('target_value_text', models.CharField(blank=True, max_length=100)),
                ('actual_value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('actual_value_text', models.CharField(blank=True, max_length=100)),
                ('previous_year_actual_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('previous_year_actual_text', models.CharField(blank=True, max_length=100)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_values', to='finance.financemetric')),
            ],
            options={
                'ordering': ['year', 'month', 'metric__display_order'],
                'indexes': [models.Index(fields=['year', 'month'], name='finance_fin_year_eafc74_idx'), models.Index(fields=['fiscal_month_index'], name='finance_fin_fiscal__4a9f98_idx')],
                'unique_together': {('metric', 'year', 'month')},
            },
        ),
    ]
